version: '3.8'

services:
  video-host:
    image: video-host:latest
    ports:
      - "3000:3000"
    volumes:
      - "${VIDEOS_PATH:-./videos}:/app/videos"
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - VIDEOS_PATH=${VIDEOS_PATH}
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6381
    networks:
      - host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  host:
    external: true
    name: host